name: Deploy to S3

permissions:
  contents: read
  id-token: write
  deployments: write

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    uses: OpenNews/opennews-actions/.github/workflows/jekyll-deploy.yml@4c689dedf3558214acd7e674a62b0a65b0014048
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      production-url: https://srccon.org
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
